server:
  port: 8091
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3000/family-income-server?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 七牛云存储
oss:
  qiniu:
    domain: http://fab.file.66zx.top # 访问域名(默认使用七牛云测试域名)
    accessKey: xxxxxxxxx # 公钥
    secretKey: xxxxxxxxx # 私钥
    bucketName: xxxx  #存储空间名称

ypy:
  bucketName: xxx
  userName: xxx
  password: xxxx
  BaseUrl: http://fab.66zx.top/
